# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AssignmentProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AssignmentProject
  pod 'SwiftLint'
  target 'AssignmentProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AssignmentProjectUITests' do
    # Pods for testing
  end

end
